#hasheq((name . "benchpilot-studio")
        (display-name . "BenchPilot Studio")
        (version . "1.1.0")
        (build . 1)
        (identifier . "site.jrtx.benchpilot-studio")
        (release-channel . stable)
        (url-schemes . ())
        (file-associations . ())
        (macos-min-version . "14.0")
        (windows-min-version . "10.0.19041.0")
        (backend . "app/backend.rkt")
        (module . "backend")
        (entry . "start")
        (protocol . 1))
